name: On release tag push
on:
  workflow_dispatch:

  # Run after every release to NPM (alpha and stable)
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  get-log4brains-version:
    uses: ./.github/workflows/reusable-get-log4brains-version.yml

  wait-for-npm-version-to-be-published:
    needs: get-log4brains-version
    uses: ./.github/workflows/reusable-wait-for-npm-version-to-be-published.yml
    with:
      npm-package: log4brains
      npm-version: ${{ needs.get-log4brains-version.outputs.version }}

  load-nodejs-supported-versions:
    uses: ./.github/workflows/reusable-load-nodejs-supported-versions.yml

  e2e-tests:
    needs:
      - load-nodejs-supported-versions
      - get-log4brains-version
      - wait-for-npm-version-to-be-published
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ${{ fromJson(needs.load-supported-versions.outputs.node_versions) }}
    uses: ./.github/workflows/reusable-e2e-tests.yml
    with:
      npm-package-fullname: log4brains@${{ needs.get-log4brains-version.outputs.version }}
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}

  e2e-tests-nodejs-current:
    needs:
      - get-log4brains-version
      - wait-for-npm-version-to-be-published
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    uses: ./.github/workflows/reusable-e2e-tests.yml
    with:
      npm-package-fullname: log4brains@${{ needs.get-log4brains-version.outputs.version }}
      os: ${{ matrix.os }}
      node-version: current
      experimental: true # best effort mode
