name: On release tag push (alpha only)
on:
  workflow_dispatch:

  # Run after every alpha release to NPM
  push:
    tags:
      - v*-alpha.*

defaults:
  run:
    shell: bash

jobs:
  get-log4brains-version:
    uses: ./.github/workflows/reusable-get-log4brains-version.yml

  wait-for-npm-version-to-be-published:
    needs: get-log4brains-version
    uses: ./.github/workflows/reusable-wait-for-npm-version-to-be-published.yml
    with:
      npm-package: log4brains
      npm-version: ${{ needs.get-log4brains-version.outputs.version }}

  docker-build-and-push:
    needs: wait-for-npm-version-to-be-published
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the latest alpha Docker image
        run: MDF_BRANCH_TAG=alpha make -C docker release version-tag branch-tag
