name: Post-release Docker Hub alpha
on:
  workflow_dispatch:

  # Run after every alpha release to NPM
  push:
    tags:
      - v*-alpha.*

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and release the latest alpha Docker image
        run: MDF_BRANCH_TAG=alpha make -C docker release version-tag branch-tag
