name: Post-release Docker Hub alpha
on:
  workflow_dispatch:

  # Run after every alpha release to NPM
  push:
    tags:
      - v*-alpha.*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the latest alpha Docker image
        run: |
          export MDF_BRANCH_TAG=alpha
          i=0
          while ! make -C docker release version-tag branch-tag
          do
            if [[ ${i} -gt 20 ]]
            then
              echo "Failure for more than 10 minutes -> abort"
              exit 1
            fi

            echo "Maybe the package is not available yet on NPM. Let's wait 30s..."
            sleep 30
            ((i=i+1))
          done
