name: Scheduled E2E (stable version)
on:
  workflow_dispatch:

  # Run on every Wednesday to check possible regressions caused by dependency updates
  # Like this one: https://github.com/thomvaill/log4brains/issues/27
  schedule:
    - cron: "0 4 * * 3"

jobs:
  load-nodejs-supported-versions:
    runs-on: ubuntu-latest
    outputs:
      node_versions: ${{ steps.get-versions.outputs.node_versions }}
    steps:
      - name: Get supported Node.js versions from JSON
        id: get-versions
        run: |
          node_versions=$(cat .github/supported_nodejs_versions.json | jq -r '.versions | @json')
          echo "::set-output name=node_versions::$node_versions"

  e2e:
    needs: load-nodejs-supported-versions
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ${{ fromJson(needs.load-supported-versions.outputs.node_versions) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required by Log4brains to work correctly (needs the whole Git history)
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g log4brains
      - name: Tests # TODO: test the preview and add some assertions :-) For now we just check the exit codes. Or manage to run e2e-tests/e2e-launcher.js from here
        run: |
          log4brains --version
          log4brains init --defaults
          log4brains adr list
          log4brains build
